site_name: WPC Proclaim Reference Guide

repo_name: jackveney/wpc-proclaim
repo_url: https://github.com/jackveney/wpc-proclaim
edit_uri: ""
extra_css:
  - 'css/extra.css'

site_description: A reference guide for Proclaim.
site_author: Jack Veney
theme:
  name: material
  custom_dir: material/
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/WPC_logo.png
  favicon: assets/WPC_logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  static_templates:
    - 404.html

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2022 Jack Veney - Westminster Presbyterian Church Wooster, Ohio
plugins:
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
  - search:
      lang: en
  - redirects:
      redirect_maps:
        docs.md: documentation/index.md
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      cover: true
      back_cover: true
      cover_title: Proclaim Reference Guide
      cover_subtitle: Westminster Presbyterian Church
      cover_logo: assets/images/banner.png
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Table of Contents
      #heading_shift: false
      toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
          - 'about/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
#  - mkpdfs:
#      company: Westminster Presbyterian Church
#      author: Jack Veney
#      toc_title: Table of contents
#      output_path: pdf/documentation.pdf
#  - pdf-export:
#      verbose: true
#      media_type: print
#      enabled_if_env: ENABLE_PDF_EXPORT
#      combined: true

# Page tree
nav:
  - Home: index.md
  - About: about.md
  - Documentation: index.md
    - Documentation: 
      - Starting a New Presentation: documentation/starting_new.md
      - Editing Text Content: documentation/editing_content.md

#    - Computers:
#      - Mackey Hall Computers: documentation/turning_projector_on.md
#      - Personal Computer: documentation/turning_projector_on.md
#    - Troubleshooting:
#      - iPad Not Connecting to Sound System: documentation/turning_projector_on.md
#      - No Sound Output: documentation/turning_projector_on.md
#      - No Computer Audio Output: documentation/turning_projector_on.md
#      - No Video Output from Projector: documentation/turning_projector_on.md
  - PDF: pdf/document.pdf